### ISSUE TITLE
Transitive dependency 'attrdict' not found

### ISSUE THREAD

**Issue by acorello** [jeanslack/Videomass#149]
I tried to pip-install your package on macOS and I got an error. Apparently the wxPython version you depend on did not specify a dependency. I haven't investigated if this issue is already in wxpython backlog. Guess you may want to bump the dependency version if it gets fixed.

Full error message:

```
$ pip install videomass
Collecting videomass
  Downloading videomass-4.0.1-py3-none-any.whl (1.2 MB)
Collecting PyPubSub>=4.0.3
  Downloading Pypubsub-4.0.3-py3-none-any.whl (61 kB)
Collecting youtube-dl>=2020.1.1
  Downloading youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
Collecting yt-dlp>=2021.9.2
  Downloading yt_dlp-2022.11.11-py2.py3-none-any.whl (2.8 MB)
Collecting requests>=2.21.0
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting wxpython>=4.0.7
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/d_/fmfzzc2d37d8l9mw_2bblb8c0000gn/T/pip-install-d44rs5mb/wxpython_68fa328d33c84a89aa8ade7190cc500c/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/d_/fmfzzc2d37d8l9mw_2bblb8c0000gn/T/pip-install-d44rs5mb/wxpython_68fa328d33c84a89aa8ade7190cc500c/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]

error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

EDIT: Added relevant issues of wxPython

- https://github.com/wxWidgets/Phoenix/issues/2296
- https://github.com/wxWidgets/Phoenix/issues/2225
- https://discuss.wxpython.org/t/wxpython-install-issue-on-macos-11-6-with-pyenv-and-python-3-11-0/36203/1

**Comment by jeanslack** [comment]
@acorello 
This problem appears to affect the latest release of wxPython version 4.2.0. A possible workaround is to force the installation of wxPython to version 4.1.1, example: 

`python3 -m pip install wxPython==4.1.1`

Being a problem indirectly connected to Videomass, I close.
