### ISSUE TITLE
Videomass AppImage ImportError: libtiff.so.5

### ISSUE THREAD

**Issue by RusselNash10121** [jeanslack/Videomass#186]
**What operating system are you using?**   
openSUSE Tumbleweed x86_64 20230205
KDE Plasma 5.27 beta, python 3.10.9, libwx 3.2.1 and libtiff6 (4.5.0)

**What version of Videomass are you using and how did you install or run it?**   
4.0.2 & 4.0.5 AppImage

**Describe the bug**   
Does not open but crashes with the error:

4.0.2:
Traceback (most recent call last):
File "/tmp/.mount_VideomGjz5jN/usr/bin/videomass", line 6, in
from videomass.gui_app import main
File "/tmp/.mount_VideomGjz5jN/opt/python3.9/lib/python3.9/site-packages/videomass/gui_app.py", line 33, in
import wx
File "/tmp/.mount_VideomGjz5jN/opt/python3.9/lib/python3.9/site-packages/wx/init.py", line 17, in
from wx.core import *
File "/tmp/.mount_VideomGjz5jN/opt/python3.9/lib/python3.9/site-packages/wx/core.py", line 12, in
from ._core import *
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory

4.0.5:
Traceback (most recent call last):
File "/tmp/.mount_VideomH7pI3s/usr/bin/videomass", line 6, in
from videomass.gui_app import main
File "/tmp/.mount_VideomH7pI3s/opt/python3.9/lib/python3.9/site-packages/videomass/gui_app.py", line 31, in
import wx
File "/tmp/.mount_VideomH7pI3s/opt/python3.9/lib/python3.9/site-packages/wx/init.py", line 17, in
from wx.core import *
File "/tmp/.mount_VideomH7pI3s/opt/python3.9/lib/python3.9/site-packages/wx/core.py", line 12, in
from ._core import *
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory

**Comment by jeanslack** [comment]
The version of wxPython on Videomass AppImage is incompatible with your system. Currently Videomass AppImage has been tested on these Linux distribution: https://jeanslack.github.io/Videomass/Pages/Packages/Linux.html#appimage-format

It is to be expected that it may not work on all available distributions. I will try to do some tests on openSUSE but for now I have no solution to your problem. I'll let you know if there's any news.

**Comment by RusselNash10121** [comment]
Okay, well, at least you're aware of it.

**Comment by RusselNash10121** [comment]
IDK if it matters or not but I do not have python 3.9 installed on the system. Only 3.10(.9).

**Comment by jeanslack** [comment]
That doesn't matter, an AppImage should work completely independently of what you have installed system-wide.

**Comment by RusselNash10121** [comment]
> That doesn't matter, an AppImage should work completely independently of what you have installed system-wide.

I figured but thought I'd mention it anyway.

**Comment by jeanslack** [comment]
Meanwhile, if you want to use Videomass, you could install wxPython with your distribution's package manager and launch Videomass from the source code.

**Comment by jeanslack** [comment]
Same problem as last Manjaro release
`ImportError: libtiff.so.5: cannot open shared object file: No such file or directory`

**Comment by zz0rk** [comment]
I am running Videomass-5.0.2-x86_64. Same issue on Debian 12.

QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/tmp/.mount_Videom5ynvFX/usr/bin/videomass", line 6, in <module>
    from videomass.gui_app import main
  File "/tmp/.mount_Videom5ynvFX/opt/python3.9/lib/python3.9/site-packages/videomass/gui_app.py", line 31, in <module>
    import wx
  File "/tmp/.mount_Videom5ynvFX/opt/python3.9/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_Videom5ynvFX/opt/python3.9/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
