### ISSUE TITLE
Using relative paths when the app is portable 

### ISSUE THREAD

**Issue by jeanslack** [jeanslack/Videomass#35]
By moving the same app to multiple PCs, relative paths would make it more portable without having to reset some paths manually. 

It was talked about on https://www.portablefreeware.com/forums/viewtopic.php?p=101779#p101779

**Comment by jeanslack** [comment]
I did some tests on Windows 10, Videomass on USB flash drive does not start with relative paths enabled, the following error occurs:
```
Traceback (most recent call last):
   File "videomass", line 35, in <module>
   File "videomass3 \ vdms3.py", line 277, in main
   File "videomass3 \ vdms3.py", line 86, in __init__
   File "videomass3 \ vdms_sys \ configurator.py", line 290, in <lambda>
   File "ntpath.py", line 703, in relpath
ValueError: path is on mount 'C:', start on mount 'B:'
```

It starts only with absolute paths.

**Comment by jeanslack** [comment]
Solved with `os.getcwd()` instead `os.path.expanduser('~')`
It was obvious that expanduser was referring to "C:" drive and in a relative path of "B:" drive, "C:" could not exist.
